---
driver:
  name: vagrant

platforms:
#- name: ubuntu-10.04
#- name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: ubuntu-16.04
#- name: centos-6.7
#- name: centos-7.2 # needs systemd support?
#- name: debian-6.0.10
#- name: debian-7.8
# planned for future tested support
#- name: freebsd-9.3
#- name: freebsd-10.1
#- name: fedora-20
#- name: fedora-21
#- name: opensuse-13.1
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
  - name: windows-2012r2
    driver_config:
      communicator: winrm
      box_url: https://wrock.blob.core.windows.net/vhds/vbox2012r2.box
      customize:
        usbehci: "off"
      network:
        - ["forwarded_port", {guest: 5985, host: 5985}]
        - ["forwarded_port", {guest: 3389, host: 3389}]

verifier:
  name: inspec
  format: documentation

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

suites:
- name: default
  run_list:
    - "recipe[zabbix-agent]"
  attributes:
- name: source
  excludes:
    - windows-2012r2
    - windows-2016
  run_list:
    - "recipe[zabbix-agent]"
  attributes:
    zabbix:
      agent:
        install_method: "source"
- name: prebuild
  excludes:
    - windows-2012r2
    - windows-2016
  run_list:
    - "recipe[zabbix-agent]"
  attributes:
    zabbix:
      agent:
        install_method: "prebuild"
        version: "3.0.4"
