rvm:
- 2.1

sudo: true

env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chef/bin:/opt/chef/embedded/bin:/opt/chefdk/embedded/bin:$PATH"

addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk

script:
  - ls
  - pwd
  - bundle exec rake travis
